/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { Microsoft_AspNetCore_Mvc_ProblemDetails } from './models/Microsoft_AspNetCore_Mvc_ProblemDetails';
export type { Spotless_Application_Dtos_Admin_AdminDashboardDto } from './models/Spotless_Application_Dtos_Admin_AdminDashboardDto';
export type { Spotless_Application_Dtos_Admin_AdminDto } from './models/Spotless_Application_Dtos_Admin_AdminDto';
export type { Spotless_Application_Dtos_Admin_MostUsedServiceDto } from './models/Spotless_Application_Dtos_Admin_MostUsedServiceDto';
export type { ChatRequest } from './models/Spotless_Application_Dtos_Ai_ChatRequest';
export type { ChatResponse } from './models/Spotless_Application_Dtos_Ai_ChatResponse';
export type { Spotless_Application_Dtos_Analytics_AdminDashboardDto } from './models/Spotless_Application_Dtos_Analytics_AdminDashboardDto';
export type { Spotless_Application_Dtos_Analytics_DailyRevenueDto } from './models/Spotless_Application_Dtos_Analytics_DailyRevenueDto';
export type { Spotless_Application_Dtos_Analytics_RevenueReportDto } from './models/Spotless_Application_Dtos_Analytics_RevenueReportDto';
export type { Spotless_Application_Dtos_AuditLog_AuditLogDto } from './models/Spotless_Application_Dtos_AuditLog_AuditLogDto';
export type { Spotless_Application_Dtos_Authentication_AuthResult } from './models/Spotless_Application_Dtos_Authentication_AuthResult';
export type { Spotless_Application_Dtos_Authentication_ExternalAuthRequest } from './models/Spotless_Application_Dtos_Authentication_ExternalAuthRequest';
export type { Spotless_Application_Dtos_Cart_AddToCartDto } from './models/Spotless_Application_Dtos_Cart_AddToCartDto';
export type { Spotless_Application_Dtos_Cart_BuyNowRequest } from './models/Spotless_Application_Dtos_Cart_BuyNowRequest';
export type { Spotless_Application_Dtos_Cart_CartCheckoutRequest } from './models/Spotless_Application_Dtos_Cart_CartCheckoutRequest';
export type { Spotless_Application_Dtos_Category_CategoryDto } from './models/Spotless_Application_Dtos_Category_CategoryDto';
export type { Spotless_Application_Dtos_Category_CreateCategoryDto } from './models/Spotless_Application_Dtos_Category_CreateCategoryDto';
export type { Spotless_Application_Dtos_Category_UpdateCategoryDto } from './models/Spotless_Application_Dtos_Category_UpdateCategoryDto';
export type { Spotless_Application_Dtos_Customer_CustomerDashboardDto } from './models/Spotless_Application_Dtos_Customer_CustomerDashboardDto';
export type { Spotless_Application_Dtos_Customer_CustomerDto } from './models/Spotless_Application_Dtos_Customer_CustomerDto';
export type { Spotless_Application_Dtos_Customer_CustomerUpdateRequest } from './models/Spotless_Application_Dtos_Customer_CustomerUpdateRequest';
export type { Spotless_Application_Dtos_Customer_WalletTopUpRequest } from './models/Spotless_Application_Dtos_Customer_WalletTopUpRequest';
export type { Spotless_Application_Dtos_Driver_ApproveDriverRequest } from './models/Spotless_Application_Dtos_Driver_ApproveDriverRequest';
export type { Spotless_Application_Dtos_Driver_DriverApplicationRequest } from './models/Spotless_Application_Dtos_Driver_DriverApplicationRequest';
export type { Spotless_Application_Dtos_Driver_DriverDto } from './models/Spotless_Application_Dtos_Driver_DriverDto';
export type { Spotless_Application_Dtos_Driver_DriverStatusUpdateDto } from './models/Spotless_Application_Dtos_Driver_DriverStatusUpdateDto';
export type { Spotless_Application_Dtos_Driver_DriverUpdateRequest } from './models/Spotless_Application_Dtos_Driver_DriverUpdateRequest';
export type { Spotless_Application_Dtos_LocationDto } from './models/Spotless_Application_Dtos_LocationDto';
export type { Spotless_Application_Dtos_Notification_NotificationDto } from './models/Spotless_Application_Dtos_Notification_NotificationDto';
export type { Spotless_Application_Dtos_Order_CreateOrderDto } from './models/Spotless_Application_Dtos_Order_CreateOrderDto';
export type { Spotless_Application_Dtos_Order_CreateOrderItemDto } from './models/Spotless_Application_Dtos_Order_CreateOrderItemDto';
export type { Spotless_Application_Dtos_Order_OrderDto } from './models/Spotless_Application_Dtos_Order_OrderDto';
export type { Spotless_Application_Dtos_Order_OrderItemDto } from './models/Spotless_Application_Dtos_Order_OrderItemDto';
export type { Spotless_Application_Dtos_Payment_InitiatePaymentDto } from './models/Spotless_Application_Dtos_Payment_InitiatePaymentDto';
export type { Spotless_Application_Dtos_Payment_InitiatePaymentResponseDto } from './models/Spotless_Application_Dtos_Payment_InitiatePaymentResponseDto';
export type { Spotless_Application_Dtos_Payment_PaymentDto } from './models/Spotless_Application_Dtos_Payment_PaymentDto';
export type { Spotless_Application_Dtos_PaymentMethods_PaymentMethodDto } from './models/Spotless_Application_Dtos_PaymentMethods_PaymentMethodDto';
export type { Spotless_Application_Dtos_Responses_PagedResponse_1 } from './models/Spotless_Application_Dtos_Responses_PagedResponse_1';
export type { Spotless_Application_Dtos_Review_CreateReviewDto } from './models/Spotless_Application_Dtos_Review_CreateReviewDto';
export type { Spotless_Application_Dtos_Review_ReviewDto } from './models/Spotless_Application_Dtos_Review_ReviewDto';
export type { Spotless_Application_Dtos_Service_ServiceDto } from './models/Spotless_Application_Dtos_Service_ServiceDto';
export type { Spotless_Application_Dtos_Settings_SystemSettingDto } from './models/Spotless_Application_Dtos_Settings_SystemSettingDto';
export type { Spotless_Application_Dtos_Settings_UpdateSystemSettingDto } from './models/Spotless_Application_Dtos_Settings_UpdateSystemSettingDto';
export type { Spotless_Application_Features_Authentication_Commands_ChangePassword_ChangePasswordCommand } from './models/Spotless_Application_Features_Authentication_Commands_ChangePassword_ChangePasswordCommand';
export type { Spotless_Application_Features_Authentication_Commands_ForgotPassword_ForgotPasswordCommand } from './models/Spotless_Application_Features_Authentication_Commands_ForgotPassword_ForgotPasswordCommand';
export type { Spotless_Application_Features_Authentication_Commands_LoginCommand_LoginCommand } from './models/Spotless_Application_Features_Authentication_Commands_LoginCommand_LoginCommand';
export type { Spotless_Application_Features_Authentication_Commands_RefreshToken_RefreshTokenCommand } from './models/Spotless_Application_Features_Authentication_Commands_RefreshToken_RefreshTokenCommand';
export type { Spotless_Application_Features_Authentication_Commands_ResetPassword_ResetPasswordCommand } from './models/Spotless_Application_Features_Authentication_Commands_ResetPassword_ResetPasswordCommand';
export type { Spotless_Application_Features_Authentication_Commands_SendOtp_SendOtpCommand } from './models/Spotless_Application_Features_Authentication_Commands_SendOtp_SendOtpCommand';
export type { Spotless_Application_Features_Authentication_Commands_SendVerificationEmail_SendVerificationEmailCommand } from './models/Spotless_Application_Features_Authentication_Commands_SendVerificationEmail_SendVerificationEmailCommand';
export type { Spotless_Application_Features_Authentication_Commands_VerifyOtp_VerifyOtpCommand } from './models/Spotless_Application_Features_Authentication_Commands_VerifyOtp_VerifyOtpCommand';
export type { Spotless_Application_Features_Customers_Commands_RegisterCustomer_RegisterCustomerCommand } from './models/Spotless_Application_Features_Customers_Commands_RegisterCustomer_RegisterCustomerCommand';
export type { Spotless_Application_Features_Drivers_Commands_AssignDriver_AssignDriverCommand } from './models/Spotless_Application_Features_Drivers_Commands_AssignDriver_AssignDriverCommand';
export type { Spotless_Application_Interfaces_PaymobProcessedCallbackData } from './models/Spotless_Application_Interfaces_PaymobProcessedCallbackData';
export type { Spotless_Domain_Enums_CustomerType } from './models/Spotless_Domain_Enums_CustomerType';
export type { Spotless_Domain_Enums_NotificationType } from './models/Spotless_Domain_Enums_NotificationType';
export type { Spotless_Domain_Enums_OrderStatus } from './models/Spotless_Domain_Enums_OrderStatus';
export type { Spotless_Domain_Enums_PaymentMethod } from './models/Spotless_Domain_Enums_PaymentMethod';
export type { Spotless_Domain_Enums_PaymentStatus } from './models/Spotless_Domain_Enums_PaymentStatus';

export { AdminsService } from './services/AdminsService';
export { AiService } from './services/AiService';
export { AnalyticsService } from './services/AnalyticsService';
export { AuditLogsService } from './services/AuditLogsService';
export { AuthService } from './services/AuthService';
export { CartsService } from './services/CartsService';
export { CategoriesService } from './services/CategoriesService';
export { CustomersService } from './services/CustomersService';
export { DriversService } from './services/DriversService';
export { NotificationsService } from './services/NotificationsService';
export { OrdersService } from './services/OrdersService';
export { PaymentsService } from './services/PaymentsService';
export { ReviewsService } from './services/ReviewsService';
export { ServicesService } from './services/ServicesService';
export { SystemSettingsService } from './services/SystemSettingsService';
